plugin_prompts:
  type: str
  help: "\n\n ******* Plugin element configuration *******"
  default: Press enter to continue
  when: "{{ 'Plugin' in elements_to_include }}"

#plugin_name:
#  type: str
#  help: What is the name of the Plugin element?
#  placeholder: "(e.g.: MyPlugin)"
#  validator: >-
#    {% if not (plugin_name | regex_search('^[A-Za-z][A-Za-z0-9 _-]*$')) %}
#    name of the plugin_name element must start with a letter and cannot contain any symbols.
#    {% endif %}
#  when: "{{ 'Plugin' in elements_to_include }}"
