plugin_prompts:
  type: str
  help: "\n\n ******* Display Pane Plugin element configuration *******\n This element does not require additional configuration."
  default: Press enter to continue
  when: "{{ 'DisplayPanePlugin' in elements_to_include }}"
