plugin_prompts:
  type: str
  help: "\n\n ******* Plugin element configuration *******\n This element does not required additional configuration."
  default: Press enter to continue
  when: "{{ 'Plugin' in elements_to_include }}"
