review:
  guidelines:
  - path: '**'
    guideline: Catch and correct any obvious bugs.
  - path: '*'
    guideline: Correct grammar mistakes. Only comment on incorrect grammar - not style.
      However, allow for flexible capitalization and abbreviation for variable names.
