#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# Get the local directory (where the script is located)
source variables.sh

# Function to create a virtual environment
create_env() {
	echo -e "\n*************************************************************"
	echo "Creating virtual environment in $VENV"
	echo -e "Using shell: $SHELL"
	if [ ! -d "$DEST_DIR" ]; then
    mkdir -p "$DEST_DIR"
  fi
  cp "$LOCAL_DIR/requirements.txt" "$DEST_DIR"
  # Check if python3 exists
   if command -v python3 &> /dev/null
   then
      python3 entrypoint.py "$DEST_DIR"
   elif command -v python &> /dev/null
   then
      python entrypoint.py "$DEST_DIR"
   else
      echo "Python is not installed. Please install Python and try again."
      exit 1
   fi
   # Write the path of the virtual environment to a file
   echo "$VENV" > "$ADDON_VENV_FILE"
}

build_project() {
  echo -e "\n*************************************************************"
  echo -e "\nBuilding seeq-addon-template project"
  "$VENV"/bin/python -m build 2>&1 | grep -v "WARNING" > /dev/null

}

install_project() {
  echo -e "\n*************************************************************"
  echo -e "\nInstalling seeq-addon-template project"
  version=$(grep 'version =' pyproject.toml | sed 's/version = //g' | tr -d '"')
  echo "seeq-addon-template version: $version"

  echo -e "\nInstalling in python environment"
  "$VENV"/bin/pip install dist/addon-"$version"-py3-none-any.whl -U > /dev/null

  if [ ! -d "$DEST_DIR/bin" ]; then
    echo "Creating directory $DEST_DIR/bin"
    mkdir -p "$DEST_DIR/bin"
  fi

  echo -e "\nCopying files to $DEST_DIR/bin"
  chmod +x "$ADDON_SCRIPT_PATH"
  chmod +x "$ADDON_VENV_FILE"
  chmod +x "$VARIABLES_FILE"
  cp "$ADDON_SCRIPT_PATH" "$ADDON_SCRIPT_LOCAL_PATH"
  cp "$ADDON_VENV_FILE" "$ADDON_VENV_FILE_LOCAL_PATH"
  cp "$VARIABLES_FILE" "$VARIABLES_FILE_LOCAL_PATH"
}

adding_to_path() {
  echo -e "\n*************************************************************"
  echo -e "\nAdding directories to your PATH"
  files_to_check=(~/.bashrc ~/.zshrc ~/.bash_profile)

  # Loop over the files
  for file in "${files_to_check[@]}"; do
      if grep -Fxq "$PATH_START_MARKER" "$file"; then
        echo "Path already in $file"
      else
        echo "Adding path to $file"
        echo "$ADD_TO_PATH" >> "$file"
      fi
  done
}

info() {
  	echo -e "\n************************************************************"
  	echo -e "\n Installation complete"
  	echo -e "\n Run 'addon --help' to see the available options"
  	echo -e "\n For example, to create an example Add-on, run the command"
  	echo -e "\n   'addon create <destination_dir>'"
  	echo -e "\n************************************************************"
}

create_env
build_project
install_project
adding_to_path
info
